baseURL = 'https://mikebinary.com/'
title = "Michael Paulauski's blog"
languageCode = 'en-us'

[taxonomies]
  tag = "tags"

[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

[params]
  description = "My personal blog. Full of tech, politics, and other nonsense. All opinions expressed here are my own and not my employers'."
  bluesky_username = "mike10010100.com"
  github_username = "mike10010100"
  bio = "Former child actor turned Dev turned DevOps Engineer. Hacking, 3D printing, IoT, and politics."
  show_excerpts = true
